sudo: required
cache: apt
before_install:
  - sudo add-apt-repository -y ppa:fish-shell/release-3
  - sudo apt-get update
  - sudo apt-get -y install fish
install:
  - export fresco_root="$HOME/.ghq"
  - export fresco_dir=$fresco_root/github.com/masa0x80/fresco
  - mkdir -p $fresco_dir
  - mv * $fresco_dir
  - export fish_conf_dir="$HOME/.config/fish/conf.d"
  - mkdir -p $fish_conf_dir
  - echo "source $fresco_dir/fresco.fish" > $fish_conf_dir/fresco.fish
script:
  - fish -c 'fresco --version'
  - fish -c 'fresco help'
  - fish -c 'fresco oh-my-fish/plugin-osx'
  - fish -c 'type -qa itunes'
  - fish -c 'fresco masa0x80/filtering_history_keybind.fish'
  - fish -c 'fresco update masa0x80/filtering_history_keybind.fish'
  - fish -c 'fresco list | grep masa0x80/angler.fish >/dev/null'
  - fish -c 'fresco list | grep masa0x80/filtering_history_keybind.fish >/dev/null'
  - fish -c 'fresco reload'
  - fish -c 'fresco remove masa0x80/filtering_history_keybind.fish'
  - fish -c 'fresco list | grep masa0x80/filtering_history_keybind.fish || true'
  - fish -c 'fresco get -abc -xyz'
  - fish -c 'fresco list | grep \\-abc || true'
  - fish -c 'fresco list | grep \\-xyz || true'
