sudo: required
cache: apt
before_install:
  - sudo add-apt-repository -y ppa:fish-shell/release-2
  - sudo apt-get update
  - sudo apt-get -y install fish
install:
  - export fresco_root="$HOME/.ghq"
  - export fresco_dir=$fresco_root/github.com/masa0x80/fresco
  - mkdir -p $fresco_dir
  - mv * $fresco_dir
  - export fish_conf_dir="$HOME/.config/fish/conf.d"
  - mkdir -p $fish_conf_dir
  - echo "source $fresco_dir/fresco.fish" > $fish_conf_dir/fresco.fish
script:
  - fish -c 'fresco --version'
  - fish -c 'fresco help'
  - fish -c 'fresco oh-my-fish/plugin-osx'
  - fish -c 'type -qa itunes'
  - fish -c 'fresco fisherman/mono'
  - fish -c 'fresco update fisherman/mono'
  - fish -c 'fresco list | grep fisherman/git_util >/dev/null'
  - fish -c 'fresco list | grep fisherman/pwd_is_home >/dev/null'
  - fish -c 'fresco list | grep fisherman/pwd_info >/dev/null'
  - fish -c 'fresco list | grep fisherman/host_info >/dev/null'
  - fish -c 'fresco list | grep fisherman/last_job_id >/dev/null'
  - fish -c 'fresco list | grep fisherman/humanize_duration >/dev/null'
  - fish -c 'fresco list | grep fisherman/mono >/dev/null'
  - fish -c 'fresco reload'
  - fish -c 'fresco remove fisherman/mono'
  - fish -c 'fresco list | grep fisherman/mono; or true'
  - fish -c 'fresco get -abc -xyz'
  - fish -c 'fresco list | grep \\-abc; or true'
  - fish -c 'fresco list | grep \\-xyz; or true'
